FROM ubuntu:19.10

RUN apt-get update && apt-get install -y \
    build-essential libssl-dev git \
    mc htop > /dev/null

RUN git clone https://github.com/wg/wrk.git wrk && \
    cd wrk && \
    make > /dev/null && \
    cp wrk /usr/local/bin

CMD tail -f /dev/null
